### ISSUE TITLE
Google Play billing library deprecation

### ISSUE THREAD

**Issue by NazimMertBilgi** [daniele-pecora/nativescript-in-app-purchase#4]
![](https://user-images.githubusercontent.com/15238282/113990317-ff706780-9859-11eb-9f87-49f96bb34111.png)

If you've recently visited your Google Play console, you might have seen this message. It appears on a NativeScript app and as it states - the app was detected to use an old version of the Google Play Billing library and it's about to get deprecated very soon.
I wonder if this plugin is going to receive such update?

@daniele-pecora

**Comment by daniele-pecora** [comment]
As soon as possible ...

Nazım Mert BİLGİ ***@***.***> schrieb am Do., 29. Juli 2021,
08:48:

**Comment by NazimMertBilgi** [comment]
Thank you so much. good work. @daniele-pecora

**Comment by daniele-pecora** [comment]
Version 2.1.0 is out.
Covers #3 and #4.
